# Generated by Django 4.2.1 on 2023-05-13 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('game', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('D', 'done'), ('Q', 'In Queue'), ('P', 'In Process')], max_length=1)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('creatred_at', models.DateTimeField(auto_now_add=True)),
                ('matches', models.ManyToManyField(to='matches.match')),
            ],
        ),
    ]
