# Generated by Django 4.2.1 on 2023-05-14 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_tournoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fifa',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='is_equal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournoment',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
