# Generated by Django 4.2.1 on 2023-05-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_fifa_lose_match_is_equal_match_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_A',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='score_B',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
